spring:
  application:
    name: prime-market-backend
  aop:
    proxy-target-class: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/prime-market-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
    baseline-on-migrate: false
security:
  jwt:
    secret: ${JWT_SECRET}
    access-token-ttl: 30m
    refresh-token-ttl: 90d
    refresh-token-cookie-name: refresh_token
    refresh-token-cookie-path: /auth
    refresh-token-cookie-same-site: Lax
    refresh-token-cookie-secure: false
logging:
  level:
    ru.maltsev.primemarketbackend: INFO
